Python da technique
dl4ab/dl4ab.github.io pull request #20
Opened 2020-09-04 06:51 UTC by diligejy

파이썬 데이터분석 실무테크닉 100 이란 책을 읽고 서평을 남겼습니다.

마음이 싱숭생숭 해서 그런지 별로 글이 맘에 안드네요.

2020-09-04 07:33 UTC, kkweon commented
왜 글이 두개? 나눠주세요.

2020-09-04 07:38 UTC, kkweon requested changes

2020-09-04 07:38 UTC, kkweon commented on source/_posts/python-data-analysis-technique.md
> +
https://hexo.io/docs/tag-plugins.html
태그닫아주세요.

2020-09-04 08:34 UTC, diligejy commented on source/_posts/python-data-analysis-technique.md
> +
해결!

2020-09-04 08:34 UTC, diligejy commented
> 왜 글이 두개? 나눠주세요.
![image](https://user-images.githubusercontent.com/40735154/92219028-efb02f80-eed4-11ea-89ed-fa9c00ff9d5c.png)

conflict가 왜 나는지 잘 모르겠습니다

2020-09-04 09:47 UTC, ssaru commented on source/_posts/python-data-analysis-technique.md
> +![책 표지](./python-data-analysis-technique/python_da.jpg)
그림이 안뜹니다.

2020-09-04 09:50 UTC, ssaru commented on source/_posts/python-data-analysis-technique.md
> +end_date에 결측이 있는 이유는 탈퇴하지 않은 회원이 탈퇴일에 공백이기 때문이라고 생각할 수 있습니다.
이 부분 문장이 이상한 것 같습니다.
`end_date`도 조금 더 자세히 설명해주면 좋을 것 같습니다.
"탈퇴하지 않은 회원이 탈퇴일에 공백"이 무슨 말인지 이해가 안갑니다.

아마 책에 내용을 인용하신거겠지만, 독자가 읽었을 때 맥락을 파악할 수 있으면 좋을 것 같습니다.

2020-09-04 09:52 UTC, ssaru commented on source/_posts/python-data-analysis-technique.md
> +"제가 반기는 것은 '도(道)'입니다. 손끝의 재주 따위보다야 우월합니다. 제가 처음 소를 잡을 때는 소만 보여 손을 댈 수 없었으나, 3년이 지나자 어느새 소의 온 모습은 눈에 띄지 않게 되었습니다. 요즘 저는 정신으로 소를 대하지 눈으로 보지는 않습니다. 눈의 작용이 멎으니 정신의 자연스런 작용만 남습니다. 그러면 천리(天理)를 따라 쇠가죽과 고기,
줄글이 너무 깁니다.
이 경우 모바일 환경에서는 읽기 매우 어렵습니다.
가독성을 위해서 중간중간 개행을 넣어주면 좋을 것 같습니다.

2020-09-04 09:54 UTC, ssaru commented
file change에 선지원 후 고민"이라는 글도 있던데 이건 뭘까요?

2020-09-05 11:06 UTC, diligejy commented on source/_posts/python-data-analysis-technique.md
> +![책 표지](./python-data-analysis-technique/python_da.jpg)
수정했습니다. 어제 대충 그냥 끄적거리다보니 꼼꼼하게 보질 못했네요. 감사합니다!

2020-09-05 11:06 UTC, diligejy commented on source/_posts/python-data-analysis-technique.md
> +end_date에 결측이 있는 이유는 탈퇴하지 않은 회원이 탈퇴일에 공백이기 때문이라고 생각할 수 있습니다.
말씀 들어보니 그렇네요. 인용을 하더라도 좀 더 읽는 사람에게 맞췄어야는데... 수정했습니다

2020-09-05 11:07 UTC, diligejy commented on source/_posts/python-data-analysis-technique.md
> +"제가 반기는 것은 '도(道)'입니다. 손끝의 재주 따위보다야 우월합니다. 제가 처음 소를 잡을 때는 소만 보여 손을 댈 수 없었으나, 3년이 지나자 어느새 소의 온 모습은 눈에 띄지 않게 되었습니다. 요즘 저는 정신으로 소를 대하지 눈으로 보지는 않습니다. 눈의 작용이 멎으니 정신의 자연스런 작용만 남습니다. 그러면 천리(天理)를 따라 쇠가죽과 고기,
지적해주신 내용 깊이 동의합니다. 읽는 분들이 보시기 편하도록 최대한 풀어서 쓰되, 특정 부분만 인용하는 걸로 바꿨습니다.

2020-09-05 11:08 UTC, diligejy commented
> file change에 선지원 후 고민"이라는 글도 있던데 이건 뭘까요?

이 부분이 뭔지 저도 잘 모르겠습니다. 저기 경모님도 지적하신거 같은데... 알아보겠습니다.

2020-09-05 11:11 UTC, diligejy commented
> 왜 글이 두개? 나눠주세요.

글이 두개가 아니라, 예전에 썼던 '선지원 후고민' 글에서 conflict가 있는거 같습니다.

![image](https://user-images.githubusercontent.com/40735154/92303845-d3cf8b00-efb3-11ea-8d35-5ebd5f2955a2.png)

예전에 github 상에서 '[존버]'라는 alt를 '[딥백수 그리고 존버]'라는 이름으로 고쳤는데, 그게 로컬 환경과 충돌이 난거 같습니다. overwrite를 한 뒤에 다시 push했습니다.

2020-09-05 11:14 UTC, diligejy commented
![image](https://user-images.githubusercontent.com/40735154/92303896-4f313c80-efb4-11ea-839c-dc3cc1066813.png)

선지원 후고민 글 local환경에서 overwrite한 뒤 
npm run format을 적용한 뒤 push 했는데도 계속 github action에서 에러가 발생하네요. 

왜 그런지 잘 모르겠습니다. 도움을 부탁드립니다.

2020-09-05 14:58 UTC, kkweon commented
일단 기본적으로 브랜치에 conflict 가 있으면 conflict 를 수정하는 걸 우선시해야 됩니다.

> This branch has conflicts that must be resolved:
> package-lock.json

그리고 package-lock.json 이 변하면 안되는데 또 변해죠. npm install format 해버려가지고 쓰지 않는 format 이라는 라이브러리가 설치된 상태입니다.

2020-09-05 15:00 UTC, kkweon requested changes
그리고 `npm run format` 치십시오

2020-09-05 15:00 UTC, kkweon commented on package-lock.json
> +    },
```suggestion
```

2020-09-05 15:00 UTC, kkweon commented on package.json
> +    "format": "^0.2.2",
```suggestion
```

2020-09-06 04:46 UTC, kkweon commented
안녕하세요. 진영님 

![image](https://user-images.githubusercontent.com/2981167/92318384-84438c00-efc0-11ea-8403-911f90b36524.png)

보면 파일이 여러개가 나오죠.

이유는 진영님이 작업하신 브랜치가 최신 브랜치가 아니었기 때문에 발생하는 것입니다.

아래 보시면 source 와 갈라진 부분이 94a0ca9 (그래서 선지원후고민 글이 반영 안된상태기 때문에 나타남) 로 매우 오래전임을 알 수 있습니다.

![image](https://user-images.githubusercontent.com/2981167/92318444-18adee80-efc1-11ea-90c2-27a1d7cad0dd.png)


다음과 같은 커맨드를 쳐주시길 바랍니다.

```shell
git checkout python_da_technique # python_da_technique 브랜치로 변경
git fetch --all # 리모트 정보 다운 받음
git merge origin/source # 최신 소스 반영
git push 
```

2020-09-06 07:44 UTC, kkweon approved these changes

2020-09-06 07:45 UTC, merged