Writing report skill 예시추가
dl4ab/dl4ab.github.io pull request #24
Opened 2020-09-11 16:56 UTC by diligejy

책에서 배웠던 예시인 빠른 실행도구를 추가하였습니다.

2020-09-11 17:09 UTC, kkweon commented
다음번에 브랜치 어떻게 만드는지 보여주세요 님 workflow 에 문제가 있어보이네요.
-- 새로운 소스에서 안따옴

2020-09-11 17:12 UTC, diligejy commented
> 다음번에 브랜치 어떻게 만드는지 보여주세요 님 workflow 에 문제가 있어보이네요.
> -- 최신 소스에서 안따옴

지금 혼자 어찌저찌 해보려고 하는 중인데 어렵네요 하하..

잠시만요

2020-09-11 17:13 UTC, kkweon commented
새로운 브랜치 만드는법

```shell
git checkout source # source 브랜치로 변경
git pull --rebase # remote에 있는 source 브랜치와 싱크
git checkout -b new-branch  # 브랜치 새로 만듬
```

님은 이 2번째를 하지 않았지.

2020-09-11 17:16 UTC, diligejy commented
> 새로운 브랜치 만드는법
> 
> ```shell
> git checkout source # source 브랜치로 변경
> git pull --rebase # remote에 있는 source 브랜치와 싱크
> git checkout -b new-branch  # 브랜치 새로 만듬
> ```
> 
> 님은 이 2번째를 하지 않았지.
> 
> 시도때도 없이 쳐야 되는 git commands
> 
> ```
> git status
> git pull --rebase
> git diff
> ```
> 
> 이걸 한번도 치지 않고 작업했다면 뭐가 잘못됬다 깨닫고 생각해보시길.

git status 하고 git pull --rebase는 했는데 git diff는 안했음

2020-09-11 17:17 UTC, kkweon commented
안했다니까 ...

2020-09-11 17:18 UTC, kkweon commented
잘못쳤는데 했다고 착각하는 거임.
 git 을 이해하지 않고 외워서 치는게 문제로 보임

2020-09-11 17:18 UTC, diligejy commented
> 안했다니까 ...

ㅇㅋ;;; 뭔가 이상하넹 이상한 곳에다가 한듯...

저번에 배우고 난 뒤 기억나서 git pull --rebase했는뎅.

2020-09-11 17:18 UTC, diligejy commented
> 잘못쳤는데 했다고 착각하는 거임.
> git 을 이해하지 않고 외워서 치는게 문제로 보임

ㅇㅇ;;;;

2020-09-13 03:37 UTC, kkweon commented
깃 해결 안함니까

2020-09-14 18:46 UTC, kkweon requested changes
중대장은 너희에게 실망했다.

2020-09-14 18:46 UTC, kkweon commented on source/_posts/writing-report-skill.md
> +<<<<<<< HEAD
```suggestion
```

2020-09-14 18:46 UTC, kkweon commented on source/_posts/writing-report-skill.md
> +=======
```suggestion
```

2020-09-14 18:46 UTC, kkweon commented on source/_posts/writing-report-skill.md
> +> > > > > > > {% endblockquote %}
```suggestion
> 바퀴를 재발명하지 마라
```

2020-09-14 21:29 UTC, diligejy commented
> 중대장은 너희에게 실망했다.

아닠ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

2020-09-18 02:35 UTC, merged