Create a new blog post lets-do-github-cli-part2
dl4ab/dl4ab.github.io pull request #34
Opened 2020-09-22 09:16 UTC by nicewook

2020-09-22 15:53 UTC, kkweon requested changes
헤더가 Title Case 가 되지 않아 본문과 잘 구분이 가지 않는 것 같습니다.
이상입니다. 수고하셨습니다.

![image](https://user-images.githubusercontent.com/2981167/93906398-fe5a5d00-fcb0-11ea-9703-f23d6aee24dc.png)

2020-09-22 15:53 UTC, kkweon commented on source/_posts/lets-do-github-cli-part2.md
> +</p>
저번에도 비슷한게 있으셨는데요. 생성해주는 곳이 이렇게 생성해주는건가요?
생성된 부분이 마음에 들지 않는군요 🤕

2020-09-22 15:53 UTC, kkweon commented on source/_posts/lets-do-github-cli-part2.md
> +## clone repo
```suggestion
## Clone repo
```

2020-09-22 15:53 UTC, kkweon commented on source/_posts/lets-do-github-cli-part2.md
> +## create repo
```suggestion
## Create repo
```

2020-09-22 15:53 UTC, kkweon commented on source/_posts/lets-do-github-cli-part2.md
> +## view repo
```suggestion
## View repo
```

2020-09-22 15:53 UTC, kkweon commented on source/_posts/lets-do-github-cli-part2.md
> +Git CLI 에서
```suggestion
GitHub CLI 에서
```

2020-09-22 23:37 UTC, nicewook commented on source/_posts/lets-do-github-cli-part2.md
> +</p>
저도 기억이 났는데 미처 찾지 못하고 PR 을 올렸습니다. 
unspash.com 아시지요? 거기껄 복붙하니 이렇게 나오네요.

2020-09-22 23:39 UTC, nicewook commented on source/_posts/lets-do-github-cli-part2.md
> +Git CLI 에서
감사합니다. 
진영님 혼나는거 보면 겁나지만 코드도 이렇게 리뷰받아보고 싶다는 욕심이 나네요. 

PR 에 대해서 리뷰하고 수정 제안을 받아들이고 하는 것들을 GitHub CLI 에서 한번 해보고 싶어서 시간이 날때에 그렇게 해보고 Resolve 하도록 하겠습니다.

2020-09-23 01:13 UTC, kkweon commented on source/_posts/lets-do-github-cli-part2.md
> +</p>
그래서 해봤는데 p align center 는 직접 추가하신거였네요. 다시 코멘트 달도록 하겠습니당.

2020-09-23 01:24 UTC, kkweon requested changes

2020-09-23 01:24 UTC, kkweon commented on source/_posts/lets-do-github-cli-part2.md
> +</p>
사용하신 문법은 올바른 HTML 이 아닙니다.
align="center" 사용하지 않습니다.

사용할때는 HTML4 나 깃헙 README.md 에서만 사용하고 저희는 HTML5 컴파일해서 사용하기 때문에 피해주세요.

```suggestion
```

2020-09-23 01:24 UTC, kkweon commented on source/_posts/lets-do-github-cli-part2.md
> +![unsplash github](./lets-do-github-cli-part2/yancy-min-842ofHC6MaI-unsplash.jpg)
두가지 방법이 있습니다

```suggestion
![Photo by Yancy Min on Unsplash](./lets-do-github-cli-part2/yancy-min-842ofHC6MaI-unsplash.jpg)
```
다른 하나는 링크도 살리는 법 그리고 HTML5 도 사용하는 법

```suggestion
<figure style="display: flex; flex-direction: column; align-items: center">
  <img src="./lets-do-github-cli-part2/yancy-min-842ofHC6MaI-unsplash.jpg">
  <figcaption>Photo by <a href="https://unsplash.com/@yancymin?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Yancy Min</a> on <a href="https://unsplash.com/s/photos/github?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></figcaption>
</figure>
```

2020-09-23 01:25 UTC, kkweon commented on source/_posts/lets-do-github-cli-part2.md
> +![unsplash github](./lets-do-github-cli-part2/yancy-min-842ofHC6MaI-unsplash.jpg)
HTML5 의 가장 큰 변화는 semantic 구조입니다. 태그 하나하나가 의미가 있어 구조를 정의합니다.
centering 같은 스타일은 전부 CSS 의 영역입니다.

2020-09-23 01:31 UTC, kkweon commented on source/_posts/lets-do-github-cli-part2.md
> +Git CLI 에서
하하 혼나다니요

٩(◕‿◕｡)۶

![image](https://user-images.githubusercontent.com/2981167/93954152-cb8c8500-fd01-11ea-8cae-e34ff3bbff8b.png)

2020-09-23 08:23 UTC, nicewook commented on source/_posts/lets-do-github-cli-part2.md
> +</p>
p align center 만 문제였던 것인가요? 
그냥 복붙을 하려니 왼쪽 정렬이 되어서 그랬던 것이거든요. 
앞으로는 figure figcaption 등의 태그를 쓰면 되려나요?

2020-09-23 08:24 UTC, nicewook commented on source/_posts/lets-do-github-cli-part2.md
> +![unsplash github](./lets-do-github-cli-part2/yancy-min-842ofHC6MaI-unsplash.jpg)
둘 중 하나를 선택하게 하는 것도 신기하네요. 언젠가 저도 써봐야겠습니다. :-)

2020-09-23 08:50 UTC, merged