블로그 포스팅 하였습니다 - Architecture by martin
dl4ab/dl4ab.github.io pull request #37
Opened 2020-09-27 09:57 UTC by nicewook

신경쓴다고 하였지만 

align 을 맞추는데 `<div style="text-align: center">` 를 쓴 부분이나 `<figure>` 태그를 쓰는 부분을 확실히 이해했는지는 모르겠습니다. 덧붙여서 이런 것들에 대해 정리한 링크가 있을까요? 즉, 이런 건 앞으로 쓰지말고, 이렇게 쓰자는 식으로 정리한 링크.

2020-09-27 10:19 UTC, kkweon requested changes
말씀하신 것들은 HTML에 관한 건데 조금 더 구체적으로 예를 들어서 슬랙에 설명헤주시면 자세히 설명드리겠습니다. 지금은 어떤 부분이 잘 모르시는건지 확실하지가 않아서 일반적인 방법을 설명드리자면 MDN 모질라 문서를 살펴 보시면 좋을 것 같습니다. 

왜 text align center하면 중앙 정렬이 되는가 그런  질문이실까요? 

한문장으로 우선 간단히 적자면 전부 "약속"입니다. 약속대로 따르면 좋은 웹사이트가 되고 나쁜 웹사이트는 브라우저와 검색엔진으로부터 차별 대우룰 받습니다.

HTML 과 CSS 도 알아야 될게 엄청 많습니다 ㅋㅋ

2020-09-27 10:19 UTC, kkweon commented on source/_posts/architecture-by-martin.md
> +<div style="text-align: center">![architecture!](./architecture-by-martin/2.png)</div>
```suggestion
![architecture!](./architecture-by-martin/2.png)
```

2020-09-27 10:19 UTC, kkweon commented on source/_posts/architecture-by-martin.md
> +<div style="text-align: center">![Design Stamina Hypothesis](./architecture-by-martin/3.png)</div>
```suggestion
![Design Stamina Hypothesis](./architecture-by-martin/3.png)
```

2020-09-27 10:20 UTC, kkweon commented on source/_posts/architecture-by-martin.md
> +<div style="text-align: center">![architecture!](./architecture-by-martin/2.png)</div>
마크다운에 필요없는 태그입니당

2020-09-27 10:22 UTC, kkweon commented on source/_posts/architecture-by-martin.md
> +<div style="text-align: center">![Design Stamina Hypothesis](./architecture-by-martin/3.png)</div>
이건 캠션에 넣으려고 하신것 같은데 출처를 그냥 줄여서 alt에 적으시면 더 간단핦 것 같습니다.


```markdown
![설명 설명 - bit ly/1234]()
```

2020-09-27 11:09 UTC, nicewook commented on source/_posts/architecture-by-martin.md
> +<div style="text-align: center">![architecture!](./architecture-by-martin/2.png)</div>
사진이 가운데 정렬이 되었으면 하는 것인데, 마크다운에서는 default 로 이미지는 center 정렬인 것인가 보군요. 
1. 그렇다면 left, right 정렬을 원하면 추가하여 명시해줘야 할까요? 
2. 일단 저는 저번에 <p algin="center"> 쓰지 말라시던게 기억나서 이걸 썼습니다.

2020-09-27 11:11 UTC, nicewook commented on source/_posts/architecture-by-martin.md
> +<div style="text-align: center">![Design Stamina Hypothesis](./architecture-by-martin/3.png)</div>
출처를 alt 에 넣으면 별도로 마우스를 가져다 대지 않으면 모르는 것이지요? 
참고하겠습니다. @@

2020-09-27 14:26 UTC, nicewook commented
음, 어딘가 꼬인거 같은데요....;;;
outdated suggestion 이 뜨면서 제안하신(?) 게 commit 이 안되네요. 제가 강제로 먹여도 되는 거죠?

2020-09-27 16:25 UTC, kkweon commented on source/_posts/architecture-by-martin.md
> +<div style="text-align: center">![Design Stamina Hypothesis](./architecture-by-martin/3.png)</div>
아니요 캡션으로 나오게 됩니다. 직접 로컬에서 돌려보시고 원하는대로 나오는지 확인해보세요. 지금은 원하시는 대로 얼라인먼트가 안 맞을 것 같아요.

2020-09-27 16:27 UTC, kkweon commented on source/_posts/architecture-by-martin.md
> +<div style="text-align: center">![architecture!](./architecture-by-martin/2.png)</div>
1. 네 그런데 여기서 문제는 마크다운과 html 혼용해서 사용하시면 안 됩니다.
2. 두 번째는 아마도 align="center" 말씀이시겠죠? 이거는 슬랙에서 답변 드리도록 하겠습니다.

2020-09-27 17:10 UTC, kkweon requested changes

2020-09-27 17:10 UTC, kkweon commented on source/_posts/architecture-by-martin.md
> +- 이미지 링크: https://drive.google.com/file/d/17xj1xjQ2Mw4XKDX5BmyFqVVFiEMiVN_L/view
```suggestion
![중요한 것 그것이 아키텍쳐이다](./architecture-by-martin/2.png)
```

1. Alt 태그는 무슨 내용인지 적어주시는게 좋습니다.
1. 이미지 링크를 적으시는건 duplicate 해보입니다. 이미 이미지가 본문에 있으니까요. 원본 이미지가 도움이 되지는 않는 것 같습니다.

2020-09-27 17:10 UTC, kkweon commented on source/_posts/architecture-by-martin.md
> +< 이미지 출처: https://martinfowler.com/bliki/DesignStaminaHypothesis.html >
이런 건 이렇게 처리해주시는게 좋은 것 같네요. 마크다운의 풋노트입니다.

```suggestion
[^stamina]![Design Stamina Hypothesis by Martin Fowler](./architecture-by-martin/3.png)

[^stamina]: 이미지 출처: https://martinfowler.com/bliki/DesignStaminaHypothesis.html
```

2020-09-27 17:17 UTC, kkweon commented
저의 리뷰는 "이런 것도 있습니다. 한번 이런 것도 알아 보세요"에 가깝습니다. 꼭 저의 스타일 대로 안 하셔도 됩니다 :O

2020-09-27 23:42 UTC, nicewook commented on source/_posts/architecture-by-martin.md
> +- 이미지 링크: https://drive.google.com/file/d/17xj1xjQ2Mw4XKDX5BmyFqVVFiEMiVN_L/view
그러게요.

2020-09-28 01:23 UTC, kkweon approved these changes
자꾸 손이 가게 되네요. 읽어보시고 정해주세요

2020-09-28 01:23 UTC, kkweon commented on source/_posts/architecture-by-martin.md
> +Design Stamina Hypothesis: https://martinfowler.com/bliki/DesignStaminaHypothesis.html
그리고 참고 링크는 마지막으로 보내시는게 좋을 것 같아요. 첫 문단은 SEO 로 등록되기 때문에 매우 중요합니다.

```suggestion
## 참고 링크

- 유튜브 링크: https://youtu.be/4E1BHTvhB7Y
- 유튜브에서 언급한 칼럼: https://martinfowler.com/ieeeSoftware/whoNeedsArchitect.pdf
- Design Stamina Hypothesis: https://martinfowler.com/bliki/DesignStaminaHypothesis.html
```

2020-09-28 01:23 UTC, kkweon commented on source/_posts/architecture-by-martin.md
> +</figure>
이 이미지 첫문단 이후로 옮겨 주실 수 있으실까요? 첫문단이 SEO 에 등록되는데 이게 첫 문단으로 인식됩니다.

2020-09-28 01:51 UTC, nicewook commented on source/_posts/architecture-by-martin.md
> +Design Stamina Hypothesis: https://martinfowler.com/bliki/DesignStaminaHypothesis.html
이것들 반영해서 commit 올리겠습니다.

2020-09-28 01:52 UTC, nicewook commented on source/_posts/architecture-by-martin.md
> +</figure>
포스팅 맨 위에 그래도 이쁜 이미지를 넣고 싶어서 넣은 것인데 첫 문단 이후로 옮기는 것은 어색해 보입니다. 그렇다면 아예 빼버리는게 낫겠지요? SEO 가 훨씬 중요하니까요.

2020-09-28 01:52 UTC, nicewook commented on source/_posts/architecture-by-martin.md
> +</figure>
미디엄 같은 경우에도 보통 시작은 이런 이쁜(?) 이미지로 시작하던데 그런 경우 SEO 와의 충돌은 어떻게 하나 궁금해지네요.

2020-09-28 01:54 UTC, kkweon commented on source/_posts/architecture-by-martin.md
> +</figure>
저희 블로그 문제입니다. 그러고보니 구동으로 넣어주시면 되겠네요 제가 살펴보겠습니다.

2020-09-28 01:57 UTC, nicewook commented on source/_posts/architecture-by-martin.md
> +</figure>
구동으로 넣어준다는게 무슨 말인지는 모르겠습니다만 이어서 이야기주시면 들여다 보겠습니다. :-)

2020-09-28 02:26 UTC, kkweon commented
아얘 삭제하셨군요. 머지하도록 하겠습니다.
수고하셨습니다.

2020-09-28 02:26 UTC, merged